### ISSUE TITLE
Inquiry about function genCOMConstraints()

### ISSUE THREAD

**Issue by TaeilJin** [loco-3d/sl1m#3]
I have a question about the function

I use a python 3 and ubuntu 18.04.

I try to study the quadruped branch. 

Inside of the genCOMConstraints, there is a com_in_limb_effector_frame_constraint.

It seems that it load existed obj files.

I thought the convex hulls will be changed by phases.

**Comment by stonneau** [comment]
Hi,
the CoM constraints only depend on the orientation of the root. So a single file (assuming identity orientation) exists, and for each phase depending on the rotation the constraint polytope is rotated based on the provided rotation matrix. 

Hope this helps ?

**Comment by TaeilJin** [comment]
I see, the polytope is a "COM workspace" which is written in sl1m paper.

![image](https://user-images.githubusercontent.com/41664042/81544696-cf52e700-93b2-11ea-9553-f71e5856c524.png)

Thank you!
