### ISSUE TITLE
Inquiry of SL1M code 

### ISSUE THREAD

**Issue by TaeilJin** [loco-3d/sl1m#5]
Dear professor,

Currently, I am studying an example of bipedal (escaliers.py), because it is difficult to understand the quadruped example (flat_ground.py) directly.

I have some questions on the SL1M code

**default_transform_from_pos_normal_(rotation[index], zero3, normals[LF])**

![image](https://user-images.githubusercontent.com/41664042/82696417-eabacd80-9ca1-11ea-84e0-a9fd692b0453.png)

- It is not well understood a geometrical meaning of that aligning the z-axis to the surface normal.

**genKinematicConstraints(left_foot_constraints,right_foot_constriants)**
I understood that the obtained inequality equation which represented as a OBJ file was written as a  local frame of the foot.

![image](https://user-images.githubusercontent.com/41664042/82696676-72084100-9ca2-11ea-8f05-480e60d405b1.png)

- Could I ask geometrical meaning of the inequality constraints?

**surfacePointsToIneq(s, n, eqAsIneq)**
![image](https://user-images.githubusercontent.com/41664042/82697217-7123df00-9ca3-11ea-87d7-2a30c7592339.png)

- Why we rotate the inequality equation by tinv?

**def MovingFootCOMConstraintInitPhase(pb, phaseDataT, A, b, startCol, endCol, startRow):**

![image](https://user-images.githubusercontent.com/41664042/82697645-45edbf80-9ca4-11ea-8b01-8cf49c98ab4a.png)
This is the function for first moving foot. 

- I am difficult to understand this coding line.

![image](https://user-images.githubusercontent.com/41664042/82697835-a54bcf80-9ca4-11ea-97fa-ca7c7cec326f.png)
I suppose that we plus two of them, like a fixed foot constraint.
![image](https://user-images.githubusercontent.com/41664042/82698326-8994f900-9ca5-11ea-8b0c-68289577172d.png)

**Comment by stonneau** [comment]
Hi.
For the future, you can directly add references (hyperlink) to pieces of code in github that will help assisting you. For instance https://github.com/loco-3d/sl1m/blob/64dca822a2fddddb8ed5fd089f67d494a836ea96/problem_definition.py#L33

Just to be clear you are currently looking that constraint files that have been defined for humanoid robots in an ad doc way used only for the biped robot. For the anymal files look here:

https://github.com/loco-3d/sl1m/blob/quadruped/stand_alone_scenarios/constraints_anymal.py

1) Given the surface normal and current root orientation, we compute the foot orientation matrix that corresponds to the foot being aligned on the surface. The z orientation of the foot is aligned with the one of the root orientation.
Thus the kinematic constraints with respect to this foot will be expressed in this frame.
Note that this only matters for the humanoid robot. For the Quadruped the contacts are considered to be 3D and this the surface orientation is not relevant for the kinematic constraints.

2) This function expresses the COM constraints in the frame of the contacting foot as a set of linear inequalities.

3) Suppose the COM x position, called cx, is constrained to be 1 meter away from the foot position px.

The constraint is written with 2 inequalities:
(cx - px) <=  1 
(cx - px) >= -1

The inequality constraints are valid for a foot position located a 0,0,0. if the position is different from the origin the constraints must be "translated" by the x position

**Comment by TaeilJin** [comment]
Thank you for answer!

To understand by comparing with paper flow, I am looking at a humanoid example first.

I really appreciate your answers.

Can I ask about the coordinates of constraints?

From my knowledge, the variable we are looking for, especially the position, is expressed in a world coordinate, but the kinematic and surface constraints are expressed in the local coordinate of the effector.

https://github.com/loco-3d/sl1m/blob/64dca822a2fddddb8ed5fd089f67d494a836ea96/constants_and_tools.py#L141

Is this code line a reason why you rotate surface inequality equation by trinv?

**Comment by stonneau** [comment]
To compute the surface inequalities, we project the surfaces in 2D and take the 2D convex hull. Indeed if the surfaces are aligned with the flat ground the 3D convex hull will fail because the dimensionality.
Once we have the inequalities we rotate them using the generic method to rotate constraints.

We thus need to use both the rotation matrix and its inverse to achieve the conversion.

I hope this is clearer

**Comment by TaeilJin** [comment]
Thank you so much professor,

I could understand the whole matrix,vector (A,b) ( A * variables <= b )
I will explain tomorrow! 

Thank you again and have a nice day!
